vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - sleistner.vscode-fileutils
    - bradlc.vscode-tailwindcss
    - oderwat.indent-rainbow
    - wix.vscode-import-cost
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - csstools.postcss
